### ISSUE TITLE
Footer logo should be on the grid - web version

### ISSUE THREAD

**Issue by danasegal1** [uidb-dev/ui-db---frontEnd#72]
The logo at the footer should be on the grid - LTR and RTL.
This is the how it looks now
<img width="840" alt="Screen Shot 2022-01-03 at 19 41 44" src="https://user-images.githubusercontent.com/95017644/147963429-5bfa4591-94ac-420b-8f3a-6f88919beccd.png">

This is how it should be
<img width="591" alt="Screen Shot 2022-01-03 at 19 58 40" src="https://user-images.githubusercontent.com/95017644/147963570-2032a980-8555-4772-90d0-84dea6b7edf1.png">

#88

**Comment by touhidbd** [comment]
Actually, I think for the responsive it's maybe okay. Because when the screen is big the shape goes to the left and misplace because this has its own container width. But small devices seem okay. This is my screenshot.

![image](https://user-images.githubusercontent.com/8915879/148497850-487e241f-6e21-4d97-9426-6f6f3b9f9bd3.png)

**Comment by danasegal1** [comment]
can you set it steady on the grid? this is my screenshoot and it doesn't look so good...
<img width="1060" alt="Screen Shot 2022-01-09 at 9 43 07" src="https://user-images.githubusercontent.com/95017644/148673726-31847637-a1d5-4ad5-9f1b-9c0242bb98bd.png">

**Comment by touhidbd** [comment]
Update. Please check

**Comment by danasegal1** [comment]
need to check again after #88
